### ISSUE TITLE
add better instructions for editing

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-portrait-TEI#14]
With screenshots, I imagine

**Comment by susannalles** [comment]
That's for sure, if you write a documentation, people will able to follow the instructions and encode the text in the same way.

**Comment by JonathanReeve** [comment]
Fixed this by adding [CONTRIBUTING.md](https://github.com/JonathanReeve/corpus-joyce-portrait-TEI/blob/gh-pages/CONTRIBUTING.md)
