### ISSUE TITLE
mark up places with geocodes

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-portrait-TEI#43]

**Comment by goldieshen** [comment]
I'll start marking up places with Geocodes in Chapter 1.

**Comment by goldieshen** [comment]
I am going to mark up locations in Chapter 1, but I don't know how to geocode. Do I use an address to longitude/latitude converter online, or should I just mark place names? How should I do this task?

**Comment by JonathanReeve** [comment]
Great! And good question. Mapping isn't my specialty, but this is my best guess: 

Before: 

```
And then we hung out at St. Stephen's Green
```

After: 

``` xml
And then we hung out at <placeName><geo>41.687142 -74.870109</geo>St. Stephen's Green</placeName>
```

**Comment by JonathanReeve** [comment]
The 41.68 is the latitude and the -74.87 is the longitude (those are made up examples).

**Comment by JonathanReeve** [comment]
Oops, [looks like I was wrong](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-location.html). Here's better markup: 

``` xml
And then we hung out at <place><location><geo>41.687142 -74.870109</geo></location><placeName>St. Stephen's Green</placeName></place>.
```

**Comment by goldieshen** [comment]
Thank you! I’ll use that format. If I can, I’ll try to make the places Stephen thought of distinct. So when you mean for the assignment, we need to mark up 20-30 lines/words/places by the deadline, you mean 20-30 marks total from any category, right? 
Again, thanks!

**Comment by JonathanReeve** [comment]
It's 20-30 lines of text, so when you're about to submit a pull request, scroll down to the list of changes, and it should say something like "Showing 1 changed file, with 20 additions and 20 deletions." Here's a screenshot: 

![pr-changes](https://cloud.githubusercontent.com/assets/1843676/18715136/2d5f9e9a-7fe6-11e6-8249-7cbcc55a5079.png)

**Comment by Alanburnett** [comment]
I am going to mark up locations in Chapter 2.

**Comment by goldieshen** [comment]
I am going to mark up Ch. 3, 4, and 5.

**Comment by JonathanReeve** [comment]
Nice! Go for it.

**Comment by JonathanReeve** [comment]
I'm very happy to be closing this issue as complete, after merging in the lastest PR!
