### ISSUE TITLE
XSLT not working on Chrome

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-portrait-TEI#47]
[The prototype transformation on github.io](http://jonathanreeve.github.io/corpus-joyce-portrait-TEI/portrait.xml) works fine on Firefox, but fails to transform correctly on Chrome and similar WebKit-based browsers. Chrome complains that "This XML file does not appear to have any style information associated with it. The document tree is shown below." 

This is very likely due to an XSL issue, since XSL complains that: 

```
runtime error: file portrait.xsl line 98 element attribute
xsl:attribute: Cannot add attributes to an element if children have been already added to the element.
```

**Comment by tcatapano** [comment]
This is because the template at line 97 matches at line 132 in the source on

```
<lg type="song">
            <l>O, the wild rose blossoms</l> 
            <l>On the little green place.</l> 
        </lg>
```

and the first thing it does is to create an attribute node, but this is illegal at this point, because an attriibute node has to precede any child element nodes of a parent element node. Could the template be changed to something like:

```
<div>
<xsl:attribute name="class">
        <xsl:value-of select="@type"/>
    </xsl:attribute>
    <p class="lg">
        <xsl:apply-templates select="@type | node()"/>
    </p>
</div>
</xsl:template>
```

**Comment by tcatapano** [comment]
Actually, if you just remove lines 98-100 of portrait.xsl, it should work.

**Comment by JonathanReeve** [comment]
Thanks for this! That got the XML transforming properly on the command-line, using `xsltproc`. I still can't get `portrait.xml` transforming directly in Chrome, but this at least allows me to generate an HTML file that I can use as a prototype page for now. Now http://jonathanreeve.github.io/corpus-joyce-portrait-TEI/index.html works. I made a `Makefile` to run the XSLT using `xsltproc`.

**Comment by tcatapano** [comment]
Yes, I've been looking into it and it looks like it is a Chrome thing. It
may have to do with Github serving the xml with the mimetype
application/xml for which Chrome will not execute the stylesheet (it may
with text/xml). Or it could be a security issue about not executing a
remote stylesheet in the brower. Not exactly sure.

**Comment by JonathanReeve** [comment]
I've moved the prototype transformed edition to Netlify, here: https://joyce-portrait.netlify.com/. It'll automatically run `make`, using the Makefile, on each commit, and show the resulting index.html. This effectively meas we don't have to maintain a gh-pages branch, or worry about how XSL works on the client side. Closing this issue.
