### ISSUE TITLE
Dubliners?

### ISSUE THREAD

**Issue by charlesreid1** [open-editions/corpus-joyce-portrait-TEI#80]
Not directly related, but curious whether open-editions has plans to create a version of the *Dubliners* corpus. I have a deep and abiding love for *Dubliners* and I'd be happy to contribute.

**Comment by JonathanReeve** [comment]
Yep, that'll probably be happening in the next few months. I've been talking with Hans Walter Gabler about it, and we're planning on starting with his edition. Expect to see it soon.

**Comment by charlesreid1** [comment]
I look forward to it!
