### ISSUE TITLE
standardize spacing at beginning of lines

### ISSUE THREAD

**Issue by HannimalCrackers** [open-editions/corpus-joyce-portrait-TEI#88]
Toward the beginning of portrait.xml, lines that have a new paragraph tag <p> are indented 5 spaces (e.g., 10077), while regular continuing lines are indented 6 spaces (e.g., 10078). 

Later in document lines with new paragraph (e.g., 21082) and regular continuing lines (e.g., 21083) are all indented the same – 5 spaces each.

What is preferred indentation formatting?

**Comment by JonathanReeve** [comment]
I think I'd actually just used my text editor to automatically indent this. Maybe I'll just do that again.
